# Generated by Django 4.0.2 on 2022-03-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='cgr_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cgr.cgr'),
        ),
    ]
