# Generated by Django 4.0.2 on 2022-03-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0003_rename_type_of_file_cgr_is_fasaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgr',
            old_name='is_FASAQ',
            new_name='is_FASTA',
        ),
    ]
