# Generated by Django 4.0.2 on 2022-03-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0004_rename_is_fasaq_cgr_is_fasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgr',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
