# Generated by Django 4.0.2 on 2022-03-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0005_cgr_img_delete_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cgr',
            old_name='k_s',
            new_name='kmer_size',
        ),
        migrations.RenameField(
            model_name='cgr',
            old_name='myfile',
            new_name='upload_file',
        ),
    ]
