# Generated by Django 4.0.2 on 2022-03-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0006_rename_k_s_cgr_kmer_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgr',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
