# Generated by Django 4.0.2 on 2022-03-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0008_alter_cgr_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgr',
            name='is_FASTA',
        ),
    ]
