# Generated by Django 4.0.2 on 2022-03-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0010_cgr_type_of_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgr',
            name='img',
            field=models.ImageField(blank=True, default='Figure_1.png', null=True, upload_to='documents/'),
        ),
    ]
