# Generated by Django 4.0.2 on 2022-03-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgr', '0011_alter_cgr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgr',
            name='type_of_file',
            field=models.CharField(choices=[('FASTA', 'FASTA'), ('FASTAQ', 'FASTAQ')], default='FASTA', max_length=8),
        ),
    ]
